export const JSONData = {
  cols: ["1", "2", "3"],
  data: [
    ["Ryder", "5190 Pharetra, St.", "Aug 21, 2021"],
    ["Sopoline", "P.O. Box 336, 8739 At Avenue", "May 23, 2021"],
    ["Colleen", "Ap #204-8297 Nec Road", "Mar 10, 2021"],
    ["Elmo", "767-8476 Nisl Ave", "Jul 26, 2021"],
    ["Zahir", "812-4858 Convallis Rd.", "Jan 21, 2021"],
    ["Tamara", "154-9717 Quam St.", "Nov 30, 2020"],
    ["Ivy", "P.O. Box 526, 5066 Pretium St.", "Feb 27, 2022"],
    ["Jordan", "119 A, Street", "Aug 8, 2021"],
    ["Tatyana", "Ap #330-3123 Eleifend, Av.", "Mar 24, 2022"],
    ["Edward", "9043 Erat. Ave", "Jul 18, 2021"],
    ["Reese", "P.O. Box 224, 2615 Morbi St.", "Jul 30, 2022"],
    ["Gray", "8847 Sed, Rd.", "Feb 23, 2022"],
    ["Ciaran", "Ap #679-9072 Sagittis Road", "Jan 29, 2021"],
    ["Nigel", "Ap #991-4448 Metus. Ave", "Nov 30, 2021"],
    ["Carol", "4039 Arcu. Street", "Nov 2, 2020"],
    ["Jamal", "Ap #373-9252 Euismod Avenue", "Jan 4, 2021"],
    ["Rylee", "P.O. Box 313, 6702 Justo. Rd.", "Sep 26, 2020"],
    ["Jolene", "Ap #215-7349 Malesuada Avenue", "Mar 7, 2021"],
    ["Asher", "127 Justo St.", "Oct 5, 2020"],
    ["Edward", "523-1484 Est, Av.", "Apr 5, 2022"],
    ["McKenzie", "9387 Posuere, St.", "Jun 2, 2022"],
    ["Mark", "379-4379 Convallis Ave", "Nov 1, 2020"],
    ["Jonas", "P.O. Box 795, 5003 Facilisis Rd.", "Feb 3, 2021"],
    ["Jade", "Ap #776-7095 Metus. Avenue", "Apr 12, 2021"],
    ["Travis", "P.O. Box 291, 2580 Ultrices Rd.", "May 3, 2021"],
    ["Shaeleigh", "Ap #835-7736 Neque Rd.", "May 27, 2022"],
    ["Imelda", "715-3078 Egestas, St.", "May 2, 2021"],
    ["Denton", "416-6571 Imperdiet, Av.", "Dec 24, 2021"],
    ["Dora", "P.O. Box 240, 9988 Ante. Ave", "Mar 29, 2022"],
    ["Colorado", "Ap #312-9555 Sem St.", "Aug 20, 2021"],
    ["Kuame", "5422 Augue. Rd.", "Feb 23, 2021"],
    ["Leslie", "Ap #458-2396 Ultricies Street", "Jun 6, 2022"],
    ["Claudia", "P.O. Box 712, 1873 Luctus Street", "Nov 24, 2021"],
    ["Christopher", "P.O. Box 981, 8985 Id, St.", "Jan 4, 2022"],
    ["Tate", "P.O. Box 488, 6593 Fringilla St.", "Jul 23, 2021"],
    ["Ferdinand", "636-8182 Justo Rd.", "Nov 5, 2020"],
    ["Asher", "Ap #188-5648 Nam Street", "Dec 8, 2021"],
    ["Jacqueline", "P.O. Box 731, 5795 Eu Rd.", "Aug 2, 2021"],
    ["Kyle", "P.O. Box 558, 2023 In Avenue", "Jul 26, 2022"],
    ["Allistair", "P.O. Box 577, 8871 Imperdiet, Road", "Nov 18, 2020"],
    ["Ebony", "Ap #876-5818 Habitant Ave", "Apr 24, 2022"],
    ["Harlan", "714-946 Vitae Avenue", "May 10, 2022"],
    ["Palmer", "3727 Hymenaeos. Rd.", "Sep 27, 2021"],
    ["Levi", "997-5150 Lacus, Rd.", "Jun 25, 2022"],
    ["Kiona", "P.O. Box 380, 9227 Amet Road", "May 23, 2021"],
    ["Galvin", "P.O. Box 364, 7720 Nisl. St.", "Sep 21, 2020"],
    ["Joshua", "180-1844 Erat. St.", "Feb 3, 2021"],
    ["Edward", "P.O. Box 377, 1213 Neque Ave", "Sep 12, 2020"],
    ["Sopoline", "634-7422 Ipsum St.", "Jan 29, 2021"],
    ["Alden", "Ap #350-6156 Curabitur Avenue", "Sep 22, 2021"],
    ["Erich", "903-4358 Morbi Rd.", "Nov 27, 2021"],
    ["Vance", "102-3888 Pede. Ave", "Jun 15, 2022"],
    ["Mason", "7204 Dis Av.", "Jan 22, 2022"],
    ["Lee", "P.O. Box 109, 7120 Aliquet Rd.", "Oct 7, 2020"],
    ["Clayton", "P.O. Box 896, 6262 Nunc. Ave", "Mar 29, 2022"],
    ["Fitzgerald", "9410 Luctus. Ave", "Sep 20, 2021"],
    ["Kameko", "Ap #820-601 At Avenue", "Mar 27, 2022"],
    ["Grady", "Ap #506-1900 Sed St.", "Jul 1, 2021"],
    ["Austin", "548-991 Eleifend Road", "Aug 26, 2020"],
    ["Sigourney", "Ap #589-6441 Pellentesque Rd.", "Feb 1, 2022"],
    ["Dara", "Ap #912-3993 Parturient St.", "May 10, 2022"],
    ["Peter", "551-734 Tincidunt Av.", "Dec 8, 2020"],
    ["Erich", "P.O. Box 737, 6866 Molestie Rd.", "May 26, 2022"],
    ["Phillip", "8736 Cum Road", "Apr 20, 2021"],
    ["Edan", "993-7167 Pellentesque St.", "Dec 1, 2021"],
    ["Devin", "7107 In, Ave", "Jun 15, 2022"],
    ["Emily", "4387 Ut Av.", "Dec 3, 2020"],
    ["Nadine", "4362 Quis Street", "Aug 29, 2020"],
    ["Allen", "Ap #443-8245 Et Rd.", "Feb 11, 2022"],
    ["Davis", "545-5163 Porttitor Avenue", "Jan 8, 2022"],
    ["Tarik", "640-9514 Tristique Rd.", "Dec 17, 2021"],
    ["Levi", "P.O. Box 951, 9288 Lorem Rd.", "Dec 14, 2020"],
    ["Dieter", "P.O. Box 135, 5228 Libero. Avenue", "Apr 13, 2022"],
    ["Abdul", "923-3571 Metus. Avenue", "Dec 11, 2021"],
    ["Julie", "Ap #623-6782 Amet St.", "Jun 10, 2021"],
    ["Jescie", "Ap #621-9490 Sapien, St.", "Jul 13, 2022"],
    ["Colleen", "Ap #222-6436 Quam Rd.", "Oct 1, 2021"],
    ["Orlando", "7592 Faucibus St.", "May 7, 2021"],
    ["Quinn", "Ap #749-5116 Rutrum Street", "Nov 18, 2020"],
    ["Colin", "1567 Vitae St.", "Sep 25, 2021"],
    ["Erin", "7689 Duis Avenue", "Jun 17, 2022"],
    ["Clio", "Ap #534-5004 Accumsan Street", "Oct 27, 2021"],
    ["Amber", "Ap #972-2193 A, Rd.", "Aug 12, 2021"],
    ["Garrett", "9686 Ut Ave", "Jul 18, 2021"],
    ["Selma", "8154 Aliquet Rd.", "Sep 5, 2020"],
    ["May", "5833 Integer Ave", "Oct 7, 2020"],
    ["Yetta", "8828 Luctus Rd.", "Dec 16, 2021"],
    ["Leroy", "P.O. Box 350, 3948 Augue Avenue", "Jul 19, 2021"],
    ["Ishmael", "425-2668 Duis Street", "Jan 7, 2022"],
    ["Rigel", "Ap #499-2749 Et St.", "Feb 23, 2021"],
    ["Britanney", "P.O. Box 819, 9874 Proin Avenue", "Dec 3, 2020"],
    ["Megan", "501-2557 Orci. Rd.", "Jun 14, 2022"],
    ["Wanda", "385-7904 Aliquam Street", "Oct 30, 2021"],
    ["Alyssa", "Ap #719-7522 Ut Avenue", "Sep 19, 2021"],
    ["Zachary", "6141 Nec, Street", "Aug 24, 2020"],
    ["Davis", "1795 Iaculis Av.", "Nov 3, 2020"],
    ["Kristen", "492-9876 Mi. St.", "Jan 21, 2022"],
    ["Rhonda", "P.O. Box 477, 2677 Vel, Ave", "Sep 24, 2021"],
    ["Halla", "3398 Magna. Av.", "Jul 22, 2021"],
    ["Keaton", "582-5055 Duis Av.", "Dec 26, 2020"],
  ],
};

export const mockDataArray1 = [
  {
    name: "Meghan M. Bush",
    date: "Aug 11, 2020",
    country: "Serbia",
    email: "Donec.dignissim@lacusvarius.co.uk",
  },
  {
    name: "Phyllis Landry",
    date: "Jan 11, 2021",
    country: "Swaziland",
    email: "cursus.luctus@duiin.edu",
  },
  {
    name: "Jasmine Nicholson",
    date: "Apr 19, 2021",
    country: "Saint Martin",
    email: "nisl.Quisque.fringilla@veliteusem.co.uk",
  },
  {
    name: "Myles Knight",
    date: "Apr 1, 2022",
    country: "Haiti",
    email: "cursus.non@auctorvitaealiquet.ca",
  },
  {
    name: "Ainsley B. Hammond",
    date: "Nov 5, 2020",
    country: "Tajikistan",
    email: "fringilla.porttitor.vulputate@egetmassaSuspendisse.net",
  },
  {
    name: "Hamish Foley",
    date: "Dec 21, 2020",
    country: "Italy",
    email: "diam.dictum.sapien@Crasloremlorem.edu",
  },
  {
    name: "Carlos Long",
    date: "Feb 5, 2021",
    country: "Congo (Brazzaville)",
    email: "lacus.pede@scelerisque.com",
  },
  {
    name: "Ashton Buckner",
    date: "Apr 22, 2022",
    country: "Macao",
    email: "nec.tempus@metus.com",
  },
  {
    name: "Keegan Norris",
    date: "Jun 21, 2022",
    country: "Lithuania",
    email: "massa.Suspendisse@vestibulumloremsit.org",
  },
  {
    name: "Nyssa M. Contreras",
    date: "Feb 16, 2021",
    country: "Tonga",
    email: "ligula.eu@fringilla.org",
  },
  {
    name: "Eugenia U. Hood",
    date: "May 2, 2021",
    country: "Libya",
    email: "magna.Sed.eu@penatibus.ca",
  },
  {
    name: "Paki N. Farley",
    date: "Nov 26, 2020",
    country: "Costa Rica",
    email: "interdum.Sed.auctor@blanditNam.edu",
  },
  {
    name: "Jasper P. Mcguire",
    date: "Jun 13, 2022",
    country: "Namibia",
    email: "in.consectetuer@vestibulumneceuismod.ca",
  },
  {
    name: "Kane W. Clarke",
    date: "Jun 22, 2021",
    country: "Ghana",
    email: "ante.Vivamus.non@tristique.net",
  },
  {
    name: "Lynn Ball",
    date: "Jan 6, 2022",
    country: "New Caledonia",
    email: "mi.Duis.risus@aliquetlobortisnisi.net",
  },
  {
    name: "Ciara Kinney",
    date: "Apr 22, 2022",
    country: "Liechtenstein",
    email: "Duis.dignissim.tempor@metus.ca",
  },
  {
    name: "Michelle Lang",
    date: "Mar 10, 2022",
    country: "Aruba",
    email: "orci@Aliquamadipiscinglobortis.edu",
  },
  {
    name: "Emerson Banks",
    date: "Dec 28, 2021",
    country: "Antarctica",
    email: "ullamcorper.Duis.cursus@lobortis.com",
  },
  {
    name: "Grant Lynn",
    date: "Apr 21, 2021",
    country: "Tonga",
    email: "sit.amet@Donecsollicitudinadipiscing.ca",
  },
  {
    name: "Daniel I. Gallagher",
    date: "Oct 13, 2020",
    country: "South Georgia and The South Sandwich Islands",
    email: "a.malesuada.id@tortorat.com",
  },
  {
    name: "Joy Melton",
    date: "Jun 8, 2021",
    country: "Niger",
    email: "lectus.ante.dictum@vehicularisus.com",
  },
  {
    name: "Jelani I. Page",
    date: "May 21, 2021",
    country: "United Arab Emirates",
    email: "eu.lacus.Quisque@gravidanunc.edu",
  },
  {
    name: "Aline L. Walker",
    date: "Nov 3, 2021",
    country: "Congo (Brazzaville)",
    email: "lacus.pede.sagittis@orciUt.edu",
  },
  {
    name: "Ruby O. Williamson",
    date: "Jun 15, 2021",
    country: "Lebanon",
    email: "Suspendisse@Vivamusnisi.net",
  },
  {
    name: "Cora I. Levy",
    date: "Apr 11, 2022",
    country: "Portugal",
    email: "interdum@vitae.edu",
  },
  {
    name: "Octavius K. Larsen",
    date: "May 20, 2022",
    country: "Montenegro",
    email: "mi.fringilla.mi@lorem.com",
  },
  {
    name: "Virginia Powers",
    date: "Jun 1, 2021",
    country: "Angola",
    email: "sem@Praesenteudui.edu",
  },
  {
    name: "Adam R. Bailey",
    date: "Feb 4, 2021",
    country: "Somalia",
    email: "molestie@faucibus.com",
  },
  {
    name: "Timothy T. Howe",
    date: "Apr 8, 2021",
    country: "Cocos (Keeling) Islands",
    email: "dui@enimcommodo.edu",
  },
  {
    name: "Abel P. Mcgee",
    date: "Mar 17, 2021",
    country: "Senegal",
    email: "accumsan@ultrices.ca",
  },
  {
    name: "Rahim N. Glover",
    date: "Mar 28, 2021",
    country: "Latvia",
    email: "orci@dictum.ca",
  },
  {
    name: "Kuame G. Fernandez",
    date: "Oct 16, 2020",
    country: "Egypt",
    email: "ullamcorper@necante.net",
  },
  {
    name: "Callum Ortega",
    date: "Oct 15, 2021",
    country: "Saint Vincent and The Grenadines",
    email: "lacus.Etiam@porttitortellusnon.ca",
  },
  {
    name: "Kim Delaney",
    date: "Mar 10, 2022",
    country: "Guinea-Bissau",
    email: "habitant@fringillaporttitorvulputate.ca",
  },
  {
    name: "Dorian Garrett",
    date: "Jul 8, 2022",
    country: "Armenia",
    email: "aliquet.vel.vulputate@commodoipsum.net",
  },
  {
    name: "Shea Buckner",
    date: "May 11, 2021",
    country: "Indonesia",
    email: "Proin.vel@estvitae.edu",
  },
  {
    name: "Maggy Fowler",
    date: "Jan 31, 2021",
    country: "Estonia",
    email: "non.lacinia.at@rutrummagnaCras.net",
  },
  {
    name: "Oleg Leach",
    date: "Feb 28, 2022",
    country: "Monaco",
    email: "nunc.id@luctus.co.uk",
  },
  {
    name: "Keelie E. Guthrie",
    date: "Apr 22, 2022",
    country: "Liberia",
    email: "nulla.Integer@interdumCurabiturdictum.ca",
  },
  {
    name: "Dante Y. Allison",
    date: "May 24, 2022",
    country: "Chile",
    email: "congue@Donec.co.uk",
  },
  {
    name: "Debra R. Ruiz",
    date: "Jan 24, 2022",
    country: "Mozambique",
    email: "eget.lacus.Mauris@nonummy.net",
  },
  {
    name: "Emmanuel W. Walters",
    date: "Aug 1, 2022",
    country: "Palau",
    email: "Nunc.mauris@odio.edu",
  },
  {
    name: "Eve M. Cohen",
    date: "Jun 19, 2022",
    country: "Cameroon",
    email: "Sed.nulla@elit.net",
  },
  {
    name: "Kylan Rios",
    date: "Jul 28, 2022",
    country: "Montserrat",
    email: "Donec@iaculisquispede.ca",
  },
  {
    name: "Natalie T. Richmond",
    date: "Jul 19, 2022",
    country: "Lesotho",
    email: "ac.libero.nec@nisiMaurisnulla.org",
  },
  {
    name: "Sonia Tillman",
    date: "Oct 21, 2020",
    country: "Liechtenstein",
    email: "tincidunt@lectusNullam.ca",
  },
  {
    name: "Yasir F. Coleman",
    date: "Jun 17, 2021",
    country: "Gabon",
    email: "libero.nec@etmagnis.org",
  },
  {
    name: "Ria Alvarado",
    date: "Sep 24, 2021",
    country: "Romania",
    email: "mollis.dui@nec.com",
  },
  {
    name: "Angelica Cummings",
    date: "Oct 24, 2021",
    country: "Northern Mariana Islands",
    email: "pede.sagittis.augue@Nunc.org",
  },
  {
    name: "Scarlet M. Randall",
    date: "Sep 11, 2021",
    country: "Gabon",
    email: "nulla@semmolestiesodales.com",
  },
  {
    name: "Charlotte Lang",
    date: "Dec 2, 2021",
    country: "Antigua and Barbuda",
    email: "lobortis.quam.a@gravidanunc.co.uk",
  },
  {
    name: "Burke C. Snyder",
    date: "Sep 4, 2020",
    country: "Vanuatu",
    email: "tristique@nibhsitamet.edu",
  },
  {
    name: "Nissim D. Roach",
    date: "Sep 6, 2021",
    country: "Gibraltar",
    email: "rutrum.non@eget.net",
  },
  {
    name: "Neve Zimmerman",
    date: "May 20, 2021",
    country: "Swaziland",
    email: "placerat@vulputatenisi.org",
  },
  {
    name: "Noble O. Durham",
    date: "Jul 8, 2022",
    country: "French Polynesia",
    email: "Pellentesque@justoPraesent.org",
  },
  {
    name: "Leonard B. Clark",
    date: "Feb 28, 2022",
    country: "Czech Republic",
    email: "nisl.Maecenas.malesuada@nonegestas.net",
  },
  {
    name: "Noah Mckee",
    date: "Oct 20, 2021",
    country: "Palestine, State of",
    email: "tempus.non.lacinia@utodio.ca",
  },
  {
    name: "Whilemina H. Thomas",
    date: "Jan 18, 2021",
    country: "Bhutan",
    email: "eu.augue.porttitor@scelerisquesedsapien.co.uk",
  },
  {
    name: "Colin F. Humphrey",
    date: "Apr 17, 2022",
    country: "Western Sahara",
    email: "ac.arcu@nectempusscelerisque.ca",
  },
  {
    name: "Rhiannon D. Nolan",
    date: "Feb 18, 2021",
    country: "Fiji",
    email: "interdum.enim@nuncacmattis.org",
  },
  {
    name: "Germane Craig",
    date: "May 4, 2021",
    country: "Christmas Island",
    email: "nisl.elementum@Vivamusrhoncus.edu",
  },
  {
    name: "Cyrus S. Leonard",
    date: "Sep 27, 2020",
    country: "French Guiana",
    email: "ridiculus@Sedetlibero.co.uk",
  },
  {
    name: "Sarah Lamb",
    date: "Oct 24, 2020",
    country: "Myanmar",
    email: "Sed@tempuseuligula.ca",
  },
  {
    name: "Brock I. England",
    date: "Nov 29, 2020",
    country: "Marshall Islands",
    email: "egestas.rhoncus@malesuadaiderat.edu",
  },
  {
    name: "Burke H. Mcintosh",
    date: "Aug 27, 2020",
    country: "Bhutan",
    email: "at@laoreetposuereenim.edu",
  },
  {
    name: "Dai Ellis",
    date: "Jan 7, 2022",
    country: "Australia",
    email: "non.hendrerit@Integer.org",
  },
  {
    name: "Rooney Gibbs",
    date: "Jan 28, 2021",
    country: "Sri Lanka",
    email: "ornare.In@eleifendCrassed.co.uk",
  },
  {
    name: "Zeus R. Gross",
    date: "Jun 15, 2021",
    country: "Trinidad and Tobago",
    email: "adipiscing.lacus.Ut@diamPellentesque.net",
  },
  {
    name: "Davis H. Bennett",
    date: "Dec 9, 2020",
    country: "Morocco",
    email: "fringilla.euismod.enim@fermentumvelmauris.ca",
  },
  {
    name: "Jeanette Simmons",
    date: "Jan 20, 2022",
    country: "Western Sahara",
    email: "nisl.arcu@Intinciduntcongue.net",
  },
  {
    name: "Ezekiel M. Mclaughlin",
    date: "Jun 2, 2022",
    country: "Malaysia",
    email: "velit.Pellentesque.ultricies@sit.ca",
  },
  {
    name: "Wing E. Mitchell",
    date: "Oct 14, 2020",
    country: "Paraguay",
    email: "arcu.Vivamus.sit@elitNulla.ca",
  },
  {
    name: "Jacob Brennan",
    date: "Dec 1, 2021",
    country: "El Salvador",
    email: "nonummy.ultricies@magna.org",
  },
  {
    name: "Declan X. Hubbard",
    date: "May 4, 2021",
    country: "Ethiopia",
    email: "euismod@odioEtiam.ca",
  },
  {
    name: "Rowan Emerson",
    date: "Dec 26, 2021",
    country: "Saint Helena, Ascension and Tristan da Cunha",
    email: "ligula.Aenean@consequatpurusMaecenas.net",
  },
  {
    name: "Malachi Black",
    date: "Mar 11, 2022",
    country: "Mali",
    email: "at@sem.edu",
  },
  {
    name: "Hasad Saunders",
    date: "Oct 29, 2021",
    country: "Mayotte",
    email: "mollis@Donecporttitor.com",
  },
  {
    name: "Yetta I. Larson",
    date: "Oct 1, 2021",
    country: "Zimbabwe",
    email: "nunc.sit.amet@aliquet.org",
  },
  {
    name: "Warren Santana",
    date: "Oct 5, 2020",
    country: "Mozambique",
    email: "dolor.vitae@NuncmaurisMorbi.com",
  },
  {
    name: "Brittany Q. Bowen",
    date: "May 24, 2022",
    country: "Mexico",
    email: "in@sagittis.net",
  },
  {
    name: "Nigel Douglas",
    date: "Jan 30, 2021",
    country: "Germany",
    email: "condimentum@anequeNullam.com",
  },
  {
    name: "Price Jacobs",
    date: "Dec 27, 2021",
    country: "Afghanistan",
    email: "tortor@Donec.edu",
  },
  {
    name: "Guy Fletcher",
    date: "Oct 18, 2021",
    country: "Swaziland",
    email: "lorem.Donec@augue.ca",
  },
  {
    name: "Dawn B. Glass",
    date: "Oct 5, 2021",
    country: "Congo (Brazzaville)",
    email: "sit@pellentesquemassa.co.uk",
  },
  {
    name: "Yolanda F. Bray",
    date: "Sep 22, 2020",
    country: "Cuba",
    email: "viverra.Donec@euultrices.com",
  },
  {
    name: "Jane O. Silva",
    date: "Mar 16, 2022",
    country: "Morocco",
    email: "luctus.ut.pellentesque@mauris.co.uk",
  },
  {
    name: "Ishmael X. Stewart",
    date: "Jan 15, 2022",
    country: "Malaysia",
    email: "Pellentesque.habitant.morbi@nec.edu",
  },
  {
    name: "Sarah Bullock",
    date: "May 1, 2022",
    country: "Serbia",
    email: "magna.sed.dui@sedturpis.net",
  },
  {
    name: "Miriam Meadows",
    date: "Sep 17, 2021",
    country: "Montserrat",
    email: "arcu@telluslorem.edu",
  },
  {
    name: "Keely Duke",
    date: "Nov 18, 2021",
    country: "Guinea",
    email: "mus.Aenean@et.ca",
  },
  {
    name: "Mollie R. Baird",
    date: "Feb 19, 2022",
    country: "Equatorial Guinea",
    email: "sollicitudin.adipiscing@dolorsit.edu",
  },
  {
    name: "Ulric G. Wells",
    date: "Jan 20, 2021",
    country: "Cayman Islands",
    email: "ac.sem.ut@placerat.ca",
  },
  {
    name: "Indigo N. Riddle",
    date: "Mar 27, 2021",
    country: "Ghana",
    email: "in@bibendumDonecfelis.co.uk",
  },
  {
    name: "Maggie W. Stephens",
    date: "Aug 14, 2021",
    country: "Chad",
    email: "malesuada.vel@mauriserat.org",
  },
  {
    name: "David Barron",
    date: "Dec 18, 2020",
    country: "India",
    email: "Quisque@ligulaDonec.ca",
  },
  {
    name: "Regina M. Padilla",
    date: "Apr 4, 2021",
    country: "Western Sahara",
    email: "commodo@auctornuncnulla.ca",
  },
  {
    name: "Timon Callahan",
    date: "Mar 7, 2021",
    country: "Sudan",
    email: "quam.dignissim.pharetra@blandit.co.uk",
  },
  {
    name: "Adria Cantu",
    date: "Jul 10, 2022",
    country: "China",
    email: "arcu.Sed@nonummy.org",
  },
  {
    name: "Lareina T. Hoover",
    date: "Jan 24, 2022",
    country: "Falkland Islands",
    email: "amet@ullamcorper.com",
  },
  {
    name: "Ciaran Noel",
    date: "Aug 14, 2020",
    country: "China",
    email: "id.risus@ac.net",
  },
];

export const mockDataArray2 = [
  {
    id: 1,
    first_name: "Ody",
    last_name: "Mateescu",
    age: 5,
    gender: "M",
  },
  {
    id: 2,
    first_name: "Fredrick",
    last_name: "Bains",
    age: 3,
    gender: "M",
  },
  {
    id: 3,
    first_name: "Waldemar",
    last_name: "Derbyshire",
    age: 11,
    gender: "M",
  },
  {
    id: 4,
    first_name: "Edsel",
    last_name: "Lammerich",
    age: 58,
    gender: "M",
  },
  {
    id: 5,
    first_name: "Darbie",
    last_name: "Kroger",
    age: 36,
    gender: "F",
  },
  {
    id: 6,
    first_name: "Michell",
    last_name: "Luthwood",
    age: 52,
    gender: "M",
  },
  {
    id: 7,
    first_name: "Dennie",
    last_name: "Lindstrom",
    age: 66,
    gender: "F",
  },
  {
    id: 8,
    first_name: "Sofia",
    last_name: "Trevain",
    age: 82,
    gender: "F",
  },
  {
    id: 9,
    first_name: "Lauree",
    last_name: "Rounds",
    age: 81,
    gender: "F",
  },
  {
    id: 10,
    first_name: "Dewain",
    last_name: "Bryett",
    age: 23,
    gender: "F",
  },
];
